### ISSUE TITLE
Only allows for a few exchanges between user and bot (companion).

### ISSUE THREAD

**Issue by WelcomedRain** [a16z-infra/companion-app#66]
After playing with this for some time over the last day, I find that only allows for a very short conversation. After a few exchanges, the dialogue gets saved to the "chatHistoryRecord" and that's the end of it. I'm not sure where this limitation is set (code or at pinecone or upstash). Do you have any insight on that? I'd like to kick the tires a bit more on the app/service but a few exchanges is pretty limiting. Thanks!

**Comment by ykhli** [comment]
@WelcomedRain Welcome!!

So every generation (both from human and from the AI) is saved in `chatHistoryRecord`, which is backed by Upstash Redis. Would love to learn more about what you meant by "I find that only allows for a very short conversation"? 

If easy, a video recording or a gif would be super helpful. Thanks agian!
