### ISSUE TITLE
How to speed up bots answers?

### ISSUE THREAD

**Issue by nttylock** [a16z-infra/companion-app#74]
Dear devs,

Could you give me please some hints, how to speed up companion answers? Because waiting time with their feedback is so long.

May be some settings in project files. Our some hints about services what app uses (I meant to upgrade something).

Thanks in advance!

**Comment by jenniferli23** [comment]
Hi there, I believe the slowness is happening to the Vicuna bot. We're working on a #[PR](https://github.com/a16z-infra/companion-app/pull/70) to speed it up. The GPT ones should be fairly fast.

**Comment by AkshayBenny** [comment]
I am using chatgpt bot and the response time for me is around 1.2 minutes on average. Is there any way to make the response faster?

**Comment by jenniferli23** [comment]
If it's with ChatGPT the response should be a lot faster than 1.2 min unless the endpoint is congested.
