### ISSUE TITLE
Can't generate embeddings

### ISSUE THREAD

**Issue by ArkfrostLumas** [a16z-infra/companion-app#89]
So I followed every step carefully, but whenever I use npm run generate-embeddings-pinecone it gives me the following error message:

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@pinecone-database/pinecone' imported from C:\[...]\companion-app\src\scripts\indexPinecone.mjs

Same with Supabase, after uncommenting it in the .env.local file:

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'dotenv' imported from C:\[...]\companion-app\src\scripts\indexPGVector.mjs

So to me it looks like in both cases it doesn't find the .env.local file to get the credentials, but I have no clue how to fix that.

![image](https://github.com/a16z-infra/companion-app/assets/39298126/bb906c03-0cdb-4513-ba15-42fad552a134)
![image](https://github.com/a16z-infra/companion-app/assets/39298126/cfd87937-7981-4555-ac1c-7b47cc197514)

**Comment by jenniferli23** [comment]
Sorry for the delay in reply here. 
It seems like your PINECONE_ENVIRONMENT variable is wrong, it should be something like `us-west-gcp`
