### ISSUE TITLE
Issue with loading companions and getting response

### ISSUE THREAD

**Issue by lsvagusa** [a16z-infra/companion-app#94]
Hi, I'm trying to use this on my local machine. I did the setup and the first page with all the companions showing is loading as it should.
After that once I prompt it with something I get the following error:

`prompt:  Hello                                                                                                       Failed to record analytics TypeError: fetch failed                                                                       at Object.fetch (node:internal/deps/undici/undici:11576:11)                                                          at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {                                    cause: Error: getaddrinfo ENOTFOUND ****                                                                                 at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)                                                     at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {                                      errno: -3008,                                                                                                        code: 'ENOTFOUND',                                                                                                   syscall: 'getaddrinfo',                                                                                              hostname: '****'                                                                                                   }                                                                                                                  }                                                                                                                    - error TypeError: fetch failed                                                                                          at Object.fetch (node:internal/deps/undici/undici:11576:11)                                                          at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {                                    cause: Error: getaddrinfo ENOTFOUND ****                                                                                 at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)                                                     at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {                                      errno: -3008,                                                                                                        code: 'ENOTFOUND',                                                                                                   syscall: 'getaddrinfo',                                                                                              hostname: '****'                                                                                                   }                                                                                                                  }   `

also when I try and load this in github workspaces no companions are loaded in, this shows instead:
![error](https://github.com/a16z-infra/companion-app/assets/126616005/4dbc8003-b06b-4c83-a469-8ec1c47f6e7f)

and then when prompting this "empty" companion I get the following:
![slika](https://github.com/a16z-infra/companion-app/assets/126616005/abff69ab-7cef-4c58-bd21-7ba33bde0859)

I've tried fixing the issue myself with no success.

**Comment by lsvagusa** [comment]
I fixed the issue with the local machine by removing typo from env.local.
The github workspaces issue still persists.

**Comment by stavroslee** [comment]
what was the typo from env.local?

**Comment by lsvagusa** [comment]
Double letter on accident.
